### ISSUE TITLE
Grouping files needed for config

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/node-template#1]
Use symbolic links so related information is kept closer together (i.e. in the grunt directory).

Depending on the use case, this might eliminate a few rc files from the root.

This is a style thing and I think it would be easier to decide in an in person dialogue.

**Comment by jrhorn424** [comment]
@gaand is this closable since removing jsbeautifier and using the `.jscsrc` file to configure the `jscs` grunt task?

**Comment by gaand** [comment]
Yes, you're solution is correct (although jsbeautifier versus jscs is a separate but not open issue).
