### ISSUE TITLE
Add grunt-nodemon back?

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/node-template#10]
Does it matter for `<js|node>-<name>[-type]` repositories?

**Comment by jrhorn424** [comment]
I'm not sure which repositories it _should_ affect, but I'm provisionally ok with putting it back into `node-template`.

**Comment by raq929** [comment]
Is this just adding a package back, or does it involve something more?

**Comment by gaand** [comment]
It may also involve adding a task.

**Comment by jrhorn424** [comment]
Was this addressed as of https://github.com/ga-wdi-boston/node-template/commit/1ffffff91c3d028984dfb8d11ee1bd1b4d88a6ec?
