### ISSUE TITLE
Use `grunt-mocha-cli` for test running?

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/node-template#16]
This solved several problems with https://github.com/ga-wdi-boston/express-api-template

 (not pushed as of this issues creation).

**Comment by jrhorn424** [comment]
Here's the commit. I believe it might be self-contained and applicable here. https://github.com/ga-wdi-boston/express-api-template/commit/6935b569b4e37998c776ef58b4cc29e6edeae351

**Comment by gaand** [comment]
Added in 1ffffff91c3d028984dfb8d11ee1bd1b4d88a6ec
