### ISSUE TITLE
Duplicate gitignore data

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/node-template#17]
```
# nyc test coverage
.nyc_output
```

In `.gitignore` twice.

**Comment by gaand** [comment]
It doesn't hurt.  It's likely an artifact of the utility that generated the file.

I would claim this is low priority, even if an easy fix.

**Comment by jrhorn424** [comment]
Addressed as of https://github.com/ga-wdi-boston/node-template/commit/99482bb95f7cd9ceb58efc1112478faf0a4e6b64

**Comment by gaand** [comment]
@payne-chris-r Please close if you concur.

**Comment by gaand** [comment]
Addressed by https://github.com/ga-wdi-boston/instructors/wiki/RepositoryRefreshFromTemplate#2-update-gitignore
