### ISSUE TITLE
Allow spaces in method shorthand syntax

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/node-template#3]
Currently:

``` diff
var y = {
-    fn () {    // BAD
+    fn() {     // GOOD
       return 42;
    }
}
```

I prefer the space (as does Ember), but I don't mind if it is missing. Change to `.jscsrc`, please add alphabetically by key:

``` diff
+   "disallowSpaceAfterObjectKeys": {
+    "allExcept": ["method"] 
+  },
```

**Comment by gaand** [comment]
@jrhorn424 Thoughts on this:

``` js
const fn = function () {
    return 42;
};

let o = {
  fn,
};
```

versus this:

``` js
let o = {
  fn () {
    return 42;
  },
};
```

?

Does it depend?  With closures?  I don't know enough about ember to say how that influences the preferred syntax, but I think I prefer the former.

**Comment by jrhorn424** [comment]
It's idiomatic in Ember to define methods inline while inheriting (extending) another object. The usual pattern looks like:

``` js
import Ember from 'ember';

export default Ember.Component.extend({
  actions: {
    close () {
      return this.sendAction('close');
    }
  }
});
```

So the linter change allows this sort of code. In general, as you do, I prefer defining methods separately from the export.

**Comment by jrhorn424** [comment]
This also makes the linting for method shorthand consistent with linting for function definitions, which allows a space before parens.

**Comment by gaand** [comment]
So, do we require the space?  From `node-template`

``` json
  "requireSpacesInAnonymousFunctionExpression": {
    "beforeOpeningRoundBrace": true,
    "beforeOpeningCurlyBrace": true
  },
```

I actually prefer no space, but perhaps consistency should win.

**Comment by jrhorn424** [comment]
There were inconsistencies between the linter in atom and the linter on the command line. I was under the impression that the AirBnB preset used spaces, so when I declared those settings explicitly, the inconsistency in tools was addressed.

Inelegant, but works.
