### ISSUE TITLE
Add `bin/example.js`

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/node-template#8]
and update `package.json` to include:

``` json
"scripts": {
  "start" : "node bin/example.js"
  }
}
```

**Comment by jrhorn424** [comment]
Does 719308da73974f address this?

**Comment by jrhorn424** [comment]
In my opinion this was subsumed in https://github.com/ga-wdi-boston/node-template/commit/1ffffff91c3d028984dfb8d11ee1bd1b4d88a6ec (`bin/index.js`).

**Comment by gaand** [comment]
Agreed.
